// <auto-generated />
using System;
using BamawWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BamawWebApi.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20260909122227_changeotpverificationmodel")]
    partial class changeotpverificationmodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BamawWebApi.Models.BookmarkFavorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<long>("CarListingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CarListingId");

                    b.HasIndex("CarListingId");

                    b.ToTable("BookmarkFavorites");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.BodyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("BodyType");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Website")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.BrandVehicleType", b =>
                {
                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("BrandId", "VehicleTypeId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("BrandVehicleTypes");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.MarketPeriodTrim", b =>
                {
                    b.Property<int>("ModelMarketPeriodId")
                        .HasColumnType("int");

                    b.Property<int>("TrimId")
                        .HasColumnType("int");

                    b.HasKey("ModelMarketPeriodId", "TrimId");

                    b.HasIndex("TrimId");

                    b.ToTable("MarketPeriodTrims");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.ModelMarketPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("ModelMarketPeriods");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.Trim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BodyTypId")
                        .HasColumnType("int");

                    b.Property<int>("BodyTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UsageTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("UsageTypeId");

                    b.ToTable("Trims");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.UsageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("UsageType");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId", "VehicleTypeId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.BodyCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("BodyConditions");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.CarListing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("BodyConditionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CashAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeliveryCarTime")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryTime")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("ExteriorColorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FirstDownPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("FreeZonePlate")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("InstallmentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("InstallmentCount")
                        .HasColumnType("int");

                    b.Property<int?>("InteriorColorId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentDue")
                        .HasColumnType("int");

                    b.Property<int>("PriceType")
                        .HasColumnType("int");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("SecondDownPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TrimId")
                        .HasColumnType("int");

                    b.Property<int>("UsageStatus")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BodyConditionId");

                    b.HasIndex("ExteriorColorId");

                    b.HasIndex("InteriorColorId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PackageId");

                    b.HasIndex("TrimId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("CarListings");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.ListingMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CarListingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CarListingId");

                    b.ToTable("ListingMedias");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.PackageOption", b =>
                {
                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("PackageId", "OptionId");

                    b.HasIndex("OptionId");

                    b.ToTable("PackageOptions");
                });

            modelBuilder.Entity("BamawWebApi.Models.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("BamawWebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsMobileVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BamawWebApi.Models.BookmarkFavorite", b =>
                {
                    b.HasOne("BamawWebApi.Models.Listing.CarListing", "CarListing")
                        .WithMany("BookmarkFavorites")
                        .HasForeignKey("CarListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BamawWebApi.Models.User", "User")
                        .WithMany("BookmarkFavorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarListing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.BodyType", b =>
                {
                    b.HasOne("BamawWebApi.Models.Catalog.VehicleType", "VehicleType")
                        .WithMany("BodyTypes")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.BrandVehicleType", b =>
                {
                    b.HasOne("BamawWebApi.Models.Catalog.Brand", "Brand")
                        .WithMany("BrandVehicleTypes")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BamawWebApi.Models.Catalog.VehicleType", "VehicleType")
                        .WithMany("BrandVehicleTypes")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.MarketPeriodTrim", b =>
                {
                    b.HasOne("BamawWebApi.Models.Catalog.ModelMarketPeriod", "ModelMarketPeriod")
                        .WithMany()
                        .HasForeignKey("ModelMarketPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BamawWebApi.Models.Catalog.Trim", "Trim")
                        .WithMany("MarketPeriodTrims")
                        .HasForeignKey("TrimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelMarketPeriod");

                    b.Navigation("Trim");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.ModelMarketPeriod", b =>
                {
                    b.HasOne("BamawWebApi.Models.Catalog.VehicleModel", "VehicleModel")
                        .WithMany()
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.Trim", b =>
                {
                    b.HasOne("BamawWebApi.Models.Catalog.BodyType", "BodyType")
                        .WithMany("Trims")
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BamawWebApi.Models.Catalog.UsageType", "UsageType")
                        .WithMany("Trims")
                        .HasForeignKey("UsageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("UsageType");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.UsageType", b =>
                {
                    b.HasOne("BamawWebApi.Models.Catalog.VehicleType", "VehicleType")
                        .WithMany("UsageTypes")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.VehicleModel", b =>
                {
                    b.HasOne("BamawWebApi.Models.Catalog.BrandVehicleType", "BrandVehicleType")
                        .WithMany("VehicleModels")
                        .HasForeignKey("BrandId", "VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BrandVehicleType");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.CarListing", b =>
                {
                    b.HasOne("BamawWebApi.Models.Listing.BodyCondition", "BodyCondition")
                        .WithMany()
                        .HasForeignKey("BodyConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BamawWebApi.Models.Listing.Color", "ExteriorColor")
                        .WithMany()
                        .HasForeignKey("ExteriorColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BamawWebApi.Models.Listing.Color", "InteriorColor")
                        .WithMany()
                        .HasForeignKey("InteriorColorId");

                    b.HasOne("BamawWebApi.Models.Listing.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BamawWebApi.Models.Listing.Package", "Package")
                        .WithMany("Listings")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BamawWebApi.Models.Catalog.Trim", "Trim")
                        .WithMany()
                        .HasForeignKey("TrimId");

                    b.HasOne("BamawWebApi.Models.User", "User")
                        .WithMany("CarListings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BamawWebApi.Models.Catalog.VehicleModel", "VehicleModel")
                        .WithMany()
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyCondition");

                    b.Navigation("ExteriorColor");

                    b.Navigation("InteriorColor");

                    b.Navigation("Location");

                    b.Navigation("Package");

                    b.Navigation("Trim");

                    b.Navigation("User");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.ListingMedia", b =>
                {
                    b.HasOne("BamawWebApi.Models.Listing.CarListing", "CarListing")
                        .WithMany("ListingMedias")
                        .HasForeignKey("CarListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarListing");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.Location", b =>
                {
                    b.HasOne("BamawWebApi.Models.Listing.Location", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.PackageOption", b =>
                {
                    b.HasOne("BamawWebApi.Models.Listing.Option", "Option")
                        .WithMany("PackageOptions")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BamawWebApi.Models.Listing.Package", "Package")
                        .WithMany("PackageOptions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.BodyType", b =>
                {
                    b.Navigation("Trims");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.Brand", b =>
                {
                    b.Navigation("BrandVehicleTypes");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.BrandVehicleType", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.Trim", b =>
                {
                    b.Navigation("MarketPeriodTrims");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.UsageType", b =>
                {
                    b.Navigation("Trims");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.VehicleType", b =>
                {
                    b.Navigation("BodyTypes");

                    b.Navigation("BrandVehicleTypes");

                    b.Navigation("UsageTypes");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.CarListing", b =>
                {
                    b.Navigation("BookmarkFavorites");

                    b.Navigation("ListingMedias");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.Location", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.Option", b =>
                {
                    b.Navigation("PackageOptions");
                });

            modelBuilder.Entity("BamawWebApi.Models.Listing.Package", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("PackageOptions");
                });

            modelBuilder.Entity("BamawWebApi.Models.User", b =>
                {
                    b.Navigation("BookmarkFavorites");

                    b.Navigation("CarListings");
                });
#pragma warning restore 612, 618
        }
    }
}
