// <auto-generated />
using BamawWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BamawWebApi.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20260907165628_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BamawWebApi.Models.Catalog.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Website")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.BrandVehicleType", b =>
                {
                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("BrandId", "VehicleTypeId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("BrandVehicleTypes");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.Generation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.Property<int>("VehicleModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleModelId");

                    b.ToTable("Generations");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.Trim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GenerationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId");

                    b.ToTable("Trims");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId", "VehicleTypeId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.BrandVehicleType", b =>
                {
                    b.HasOne("BamawWebApi.Models.Catalog.Brand", "Brand")
                        .WithMany("BrandVehicleTypes")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BamawWebApi.Models.Catalog.VehicleType", "VehicleType")
                        .WithMany("BrandVehicleTypes")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.Generation", b =>
                {
                    b.HasOne("BamawWebApi.Models.Catalog.VehicleModel", "VehicleModel")
                        .WithMany("Generations")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.Trim", b =>
                {
                    b.HasOne("BamawWebApi.Models.Catalog.Generation", "Generation")
                        .WithMany("Trims")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.VehicleModel", b =>
                {
                    b.HasOne("BamawWebApi.Models.Catalog.BrandVehicleType", "BrandVehicleType")
                        .WithMany("VehicleModels")
                        .HasForeignKey("BrandId", "VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BrandVehicleType");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.Brand", b =>
                {
                    b.Navigation("BrandVehicleTypes");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.BrandVehicleType", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.Generation", b =>
                {
                    b.Navigation("Trims");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.VehicleModel", b =>
                {
                    b.Navigation("Generations");
                });

            modelBuilder.Entity("BamawWebApi.Models.Catalog.VehicleType", b =>
                {
                    b.Navigation("BrandVehicleTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
